// Common endgame weekly bosses, hardest tiers first.
// Users can add custom ones too, so this is just a starting catalog.
export const BOSS_PRESETS = [
  'Hard Limbo',
  'Extreme Kaling',
  'Extreme Kalos',
  'Extreme Seren',
  'Extreme Black Mage',
  'Hard Kaling',
  'Chaos Kalos',
  'Hard Seren',
  'Hard Black Mage',
  'Hard Verus Hilla',
  'Hard Darknell',
  'Chaos Gloom',
  'Hard Will',
  'Hard Lucid',
  'Hard Damien',
  'Hard Lotus',
  'Normal Limbo',
  'Normal Kaling',
  'Normal Kalos',
  'Normal Seren',
  'Normal Verus Hilla',
  'Normal Darknell',
  'Normal Gloom',
  'Normal Will',
  'Normal Lucid',
  'Normal Damien',
  'Normal Lotus',
]
